name: assignment1
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  responsive_framework: ^0.2.0


  flutter:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  fl_chart: ^0.61.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - images/waiting.png
  fonts:
    - family: OpenSans
      fonts:
         - asset: fonts/OpenSans-Regular.ttf
         - asset: fonts/OpenSans-Bold.ttf
           weight: 700
    - family: Quicksand
      fonts:
         - asset: fonts/Quicksand-Regular.ttf
         - asset: fonts/Quicksand-Bold.ttf
           weight: 700

